let TestableAcfVersesOT = [
  ".bv Gênesis 1:3 ACF",
  ".bv Êxodo 1:3 ACF",
  ".bv Levítico 1:3 ACF",
  ".bv Números 1:3 ACF",
  ".bv Deuteronômio 1:3 ACF",
  ".bv Josué 1:3 ACF",
  ".bv Juízes 1:3 ACF",
  ".bv Rute 1:3 ACF",
  ".bv I Samuel 1:3 ACF",
  ".bv II Samuel 1:3 ACF",
  ".bv I Reis 1:3 ACF",
  ".bv II Reis 1:3 ACF",
  ".bv I Crônicas 1:3 ACF",
  ".bv II Crônicas 1:3 ACF",
  ".bv Esdras 1:3 ACF",
  ".bv Neemias 1:3 ACF",
  ".bv Ester 1:3 ACF",
  ".bv Jó 1:3 ACF",
  ".bv Salmos 1:3 ACF",
  ".bv Provérbios 1:3 ACF",
  ".bv Eclesiastes 1:3 ACF",
  ".bv Cânticos dos Cânticos 1:3 ACF",
  ".bv Cantares de Salomão 1:3 ACF",
  ".bv Isaías 1:3 ACF",
  ".bv Jeremias 1:3 ACF",
  ".bv Lamentações 1:3 ACF",
  ".bv Ezequiel 1:3 ACF",
  ".bv Daniel 1:3 ACF",
  ".bv Oseias 1:3 ACF",
  ".bv Joel 1:3 ACF",
  ".bv Amós 1:3 ACF",
  ".bv Obadias 1:3 ACF",
  ".bv Jonas 1:3 ACF",
  ".bv Miqueias 1:3 ACF",
  ".bv Naum 1:3 ACF",
  ".bv Habacuque 1:3 ACF",
  ".bv Sofonias 1:3 ACF",
  ".bv Ageu 1:3 ACF",
  ".bv Zacarias 1:3 ACF",
  ".bv Malaquias 1:3 ACF"
];

let TestableAcfVersesNT = [
  ".bv Mateus 2:2 ACF",
  ".bv Marcos 2:2 ACF",
  ".bv Lucas 2:2 ACF",
  ".bv João 2:2 ACF",
  ".bv Atos 2:2 ACF",
  ".bv Romanos 2:2 ACF",
  ".bv I Coríntios 2:2 ACF",
  ".bv II Coríntios 2:2 ACF",
  ".bv Gálatas 2:2 ACF",
  ".bv Efésios 2:2 ACF",
  ".bv Filipenses 2:2 ACF",
  ".bv Colossenses 2:2 ACF",
  ".bv I Tessalonicenses 2:2 ACF",
  ".bv II Tessalonicenses 2:2 ACF",
  ".bv I Timóteo 2:2 ACF",
  ".bv II Timóteo 2:2 ACF",
  ".bv Tito 2:2 ACF",
  ".bv Filemon 1:4 ACF",
  ".bv Filemon 1:9 ACF",
  ".bv Hebreus 2:2 ACF",
  ".bv Tiago 1:12 ACF",
  ".bv I Pedro 1:2 ACF",
  ".bv II Pedro 1:2 ACF",
  ".bv I João 1:2 ACF",
  ".bv II João 1:2 ACF",
  ".bv III João 1:2 ACF",
  ".bv Judas 1:2 ACF",
  ".bv Apocalipse 10:2 ACF"
];

let TestableWpntVersesNT = [
  ".bv Mateus 2:2 WPNT",
  ".bv Marcos 2:2 WPNT",
  ".bv Lucas 2:2 WPNT",
  ".bv João 2:2 WPNT",
  ".bv Atos 2:2 WPNT",
  ".bv Romanos 2:2 WPNT",
  ".bv I Coríntios 2:2 WPNT",
  ".bv II Coríntios 2:2 WPNT",
  ".bv Gálatas 2:2 WPNT",
  ".bv Efésios 2:2 WPNT",
  ".bv Filipenses 2:2 WPNT",
  ".bv Colossenses 2:2 WPNT",
  ".bv I Tessalonicenses 2:2 WPNT",
  ".bv II Tessalonicenses 2:2 WPNT",
  ".bv I Timóteo 2:2 WPNT",
  ".bv II Timóteo 2:2 WPNT",
  ".bv Tito 2:2 WPNT",
  ".bv Filemon 1:4 WPNT",
  ".bv Filemon 1:9 WPNT",
  ".bv Hebreus 2:2 WPNT",
  ".bv Tiago 1:12 WPNT",
  ".bv I Pedro 1:2 WPNT",
  ".bv II Pedro 1:2 WPNT",
  ".bv I João 1:2 WPNT",
  ".bv II João 1:2 WPNT",
  ".bv III João 1:2 WPNT",
  ".bv Judas 1:2 WPNT",
  ".bv Apocalipse 10:2 WPNT"
];

let TestableRwpCmtNT = [
  ".bc Mateus 2:2 RWP",
  ".bc Marcos 2:2 RWP",
  ".bc Lucas 2:2 RWP",
  ".bc João 2:2 RWP",
  ".bc Atos 2:2 RWP",
  ".bc Romanos 2:2 RWP",
  ".bc I Coríntios 2:2 RWP",
  ".bc II Coríntios 2:2 RWP",
  ".bc Gálatas 2:2 RWP",
  ".bc Efésios 2:2 RWP",
  ".bc Filipenses 2:2 RWP",
  ".bc Colossenses 2:2 RWP",
  ".bc I Tessalonicenses 2:2 RWP",
  ".bc II Tessalonicenses 2:2 RWP",
  ".bc I Timóteo 2:2 RWP",
  ".bc II Timóteo 2:2 RWP",
  ".bc Tito 2:2 RWP",
  ".bc Filemon 1:4 RWP",
  ".bc Filemon 1:9 RWP",
  ".bc Hebreus 2:2 RWP",
  ".bc Tiago 1:12 RWP",
  ".bc I Pedro 1:2 RWP",
  ".bc II Pedro 1:2 RWP",
  ".bc I João 1:2 RWP",
  ".bc II João 1:2 RWP",
  ".bc III João 1:2 RWP",
  ".bc Judas 1:2 RWP",
  ".bc Apocalipse 10:2 RWP"
];
